---
version: 2.1

executors:
  yamllint:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/yamllint:latest
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  ansible-lint: orbss/ansible-lint@0.0.2
  aws-cli: circleci/aws-cli@3.1.1
  molecule-ec2: orbss/molecule-ec2@0.0.2

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-playbook-test: true
  molecule:
    executor: molecule-ec2/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: molecule_wordpress_install
          session-duration: '3600'
      - molecule-ec2/execute:
          aws-ami-name: "centos-stream8-1*"
          aws-ami-owner-id: "808683561341"
          aws-resource-name: "molecule_wordpress_install"
          aws-vpc-subnet-id: "subnet-022a704b3061b8b39"
          circleci-timeout: "15m"
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          context: AWS_OPENID_CONNECT_TOKENS
          requires:
            - ansible-lint
